import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import Container from "@/components/shared/container";

export const metadata: Metadata = {
  title: "Vibrant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="bg-white font-inter min-h-full">
        <Navbar />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
